import { mobiscroll } from '../src/js/modules/mobiscroll.angular';
export * from '../src/js/modules/mobiscroll.angular';
// import '../src/js/i18n/de';
// import '../src/js/i18n/es';
// import '../src/js/i18n/fr';
// import '../src/js/i18n/it';
// import '../src/js/i18n/zh';
// import '../src/js/themes/ios';
// import '../src/js/themes/mobiscroll-dark';
// import '../src/js/themes/material';
// import '../src/js/themes/material-dark';
// import '../src/js/themes/ios-dark';
// import '../src/js/themes/brio8themev5';
// import '../src/js/themes/auto-theme';
export default mobiscroll;
